### ISSUE TITLE
Uppdatera package-lock.json

### ISSUE THREAD

**Issue by fahlstrm** [fahlstrm/pattern-customerapp#24]
Ta bort filen, kör `npm install` och ev ng update. Bygg sedan om docker och se till att felmeddelande om old npm version/package-lock.json

**Comment by datalowe** [comment]
Fixat iom [commit #a64f96a886bf45c9858f6bb72c80ddd0262fb760](https://github.com/fahlstrm/pattern-customerapp/commit/a64f96a886bf45c9858f6bb72c80ddd0262fb760). (testat också i pattern-orchestra)
